from pathlib import Path
p=Path('app/page.tsx')
s=p.read_text()
old='''function Results({q,read,open,openUser}:{q:string;read:string[];open:(id:string)=>void;openUser:(name:string)=>void}){const n=norm(q);const found=useMemo(()=>{const tokens=q.split(/\\s+/).map(norm).filter(Boolean);return investigationPosts.filter(p=>{const hay=norm([p.title,p.author,p.excerpt,...p.body,...(p.terms||[]),p.archive||\"\",...p.replies.flatMap(r=>[r.user,r.text])].join(\" \"));return tokens.every(token=>hay.includes(token))||n===p.id})},[q,n]);const users=useMemo(()=>{const names=new Set<string>();investigationPosts.forEach(p=>{names.add(p.author);p.replies.forEach(r=>names.add(r.user))});return [...names].filter(name=>norm(name).includes(n)).slice(0,2)},[n]);return <main className=\"results\"><header><Search/><span><h2>搜索“{q}”</h2><p>公开主题 {found.length} 条{users.length?`，用户 ${users.length} 条`:\"\"}</p></span></header><section>{users.map(name=><button className=\"user-result\" onClick={()=>openUser(name)} key={name}><i>{name[0]}</i><span><b>用户：{name}</b><small>查看公开主题与回复历史</small></span><ChevronRight/></button>)}{found.map(p=><Row key={p.id} p={p} read={read.includes(p.id)} open={()=>open(p.id)}/>)}{!found.length&&!users.length&&<div className=\"empty\"><Search/><h3>没有找到匹配的公开内容</h3></div>}</section></main>}'''
new='''function Results({q,read,open,openUser}:{q:string;read:string[];open:(id:string)=>void;openUser:(name:string)=>void}){const n=norm(q);const users=useMemo(()=>{const names=new Set<string>();investigationPosts.forEach(p=>{names.add(p.author);p.replies.forEach(r=>names.add(r.user))});return [...names].filter(name=>norm(name).includes(n)).slice(0,2)},[n]);const exactUser=useMemo(()=>users.find(name=>norm(name)===n),[users,n]);const found=useMemo(()=>{const tokens=q.split(/\\s+/).map(norm).filter(Boolean);return investigationPosts.filter(p=>{if(n===p.id)return true;const directHay=norm([p.title,p.author,p.excerpt,...p.body,...(p.terms||[]),p.archive||\"\",...p.replies.map(r=>r.text)].join(\" \"));if(exactUser){return norm(p.author)===n||tokens.every(token=>directHay.includes(token));}const broadHay=norm([directHay,...p.replies.map(r=>r.user)].join(\" \"));return tokens.every(token=>broadHay.includes(token))})},[q,n,exactUser]);return <main className=\"results\"><header><Search/><span><h2>搜索“{q}”</h2><p>公开主题 {found.length} 条{users.length?`，用户 ${users.length} 条`:\"\"}</p></span></header><section>{users.map(name=><button className=\"user-result\" onClick={()=>openUser(name)} key={name}><i>{name[0]}</i><span><b>用户：{name}</b><small>查看公开主题与回复历史</small></span><ChevronRight/></button>)}{found.map(p=><Row key={p.id} p={p} read={read.includes(p.id)} open={()=>open(p.id)}/>)}{!found.length&&!users.length&&<div className=\"empty\"><Search/><h3>没有找到匹配的公开内容</h3></div>}</section></main>}'''
if old not in s:
    raise SystemExit('Results block not found')
s=s.replace(old,new)
old2='''if(phase===\"closed\")return <section style={{margin:\"18px 24px\",padding:16,border:\"1px solid #d5cabc\",background:\"#f2ede4\"}}><b style={{display:\"block\",fontSize:13}}>失效附件缓存</b><small style={{display:\"block\",margin:\"5px 0 12px\",color:\"#81766d\"}}>thumb_2012_0712.jpg · 恢复状态异常</small><button onClick={()=>setPhase(\"error\")} style={{padding:\"7px 11px\",border:\"1px solid #b8afa5\",background:\"#fff\",borderRadius:5}}>打开恢复附件</button></section>;'''
new2='''if(phase===\"closed\")return <section style={{margin:\"18px 24px\",padding:16,border:\"1px solid #d5cabc\",background:\"#f2ede4\"}}><div style={{display:\"flex\",alignItems:\"center\",gap:8,marginBottom:5}}><b style={{fontSize:13}}>失效附件</b><em style={{padding:\"2px 6px\",borderRadius:4,background:\"#ead8d3\",color:\"#8d3e35\",fontSize:10,fontStyle:\"normal\"}}>恢复失败</em></div><small style={{display:\"block\",margin:\"0 0 12px\",color:\"#81766d\"}}>thumb_2012_0712.jpg</small><button onClick={()=>setPhase(\"error\")} style={{padding:\"7px 11px\",border:\"1px solid #b8afa5\",background:\"#fff\",borderRadius:5}}>打开附件</button></section>;'''
if old2 not in s:
    raise SystemExit('attachment block not found')
s=s.replace(old2,new2)
p.write_text(s)
