"use client";
/* eslint-disable @next/next/no-img-element */
import {ReactNode,useEffect,useMemo,useState} from "react";
import {ArrowLeft,ChevronRight,Clock3,Globe2,History as HistoryIcon,Home,LockKeyhole,Maximize2,MessageCircle,Minimize2,NotebookPen,RefreshCw,Search,Wifi,X} from "lucide-react";
import {history,Post,posts,privateEntries,profile} from "../content/gameDataFlowV2";
import LocalVault from "./LocalVault";
import InteractiveWechat,{SharedMaterial} from "./InteractiveWechat";
import PrivateArea from "./PrivateArea";
import AdminPortal from "./AdminPortal";

type App="browser"|"wechat"|"notes"|"verse";
type Route={kind:"home"}|{kind:"post",id:string}|{kind:"profile"}|{kind:"user",name:string}|{kind:"private"}|{kind:"history"}|{kind:"search",q:string}|{kind:"account"};

const contextPosts:Post[]=[];
const investigationPosts=posts;
const investigationPrivateEntries=privateEntries;
const SHAREABLE_POST_IDS=new Set(["33897","09114","09831","10731","14692","17428","11208","27614"]);
const HOME_POST_IDS=["34091","34086","34080","34064","34055","34049","20847","34043","33992","33981"];
let persistedForumIdentity:"shenyan"|"admin"="shenyan";

export default function Page(){
 const [stage,setStage]=useState<"title"|"login"|"desktop">("title");
 const [intro,setIntro]=useState(true),[app,setApp]=useState<App|null>(null),[max,setMax]=useState(true),[wxRead,setWxRead]=useState(false),[privateUnlocked,setPrivateUnlocked]=useState(false),[noteUnlocked,setNoteUnlocked]=useState(false);
 const [materials,setMaterials]=useState<SharedMaterial[]>([]);
 const [wxPost,setWxPost]=useState<string|null>(null);
 const rememberMaterial=(m:SharedMaterial)=>setMaterials(prev=>prev.some(x=>x.id===m.id)?prev:[...prev,m]);
 if(stage==="title")return <main className="title"><section><small>河临 · 2026年10月17日</small><h1>烛阴旧闻</h1><p>沈妍没有赴约。<br/>电话关机，消息也没有回复。</p><button onClick={()=>setStage("login")}>进入公寓 <ChevronRight/></button></section></main>;
 if(stage==="login")return <main className="login"><div className="clock"><b>19:06</b><span>10月17日　星期六</span></div><section><div className="avatar">妍</div><h2>沈妍</h2><button className="password" onClick={()=>setStage("desktop")}><span>••••••••</span><ChevronRight/></button><p>你和沈妍从小学低年级就认识。你们互为紧急联系人，也一直留着彼此的备用门锁密码。</p></section></main>;
 const open=(x:App)=>{setApp(x);setMax(x==="browser"||x==="verse");if(x==="wechat")setWxRead(true)};
 const appTitle=app==="browser"?"澄川浏览器":app==="wechat"?"微信":app==="notes"?"本地资料":app==="verse"?"澄川浏览器":"访达";
 return <main className="desktop"><header className="sys"><div><b>●</b><strong>{appTitle}</strong><span>文件</span><span>编辑</span></div><div><Wifi/><span>80%</span><span>10月17日 周六 19:06</span></div></header>
  <div className="shortcuts"><Icon label="浏览器" tone="blue" icon={<Globe2/>} onClick={()=>open("browser")}/><Icon label="微信" tone="green" icon={<MessageCircle/>} badge={!wxRead} onClick={()=>open("wechat")}/><Icon label="本地资料" tone="amber" icon={<NotebookPen/>} onClick={()=>open("notes")}/></div>
  {intro&&<div className="overlay"><section className="intro"><small><Clock3/> 2026年10月17日　19:06</small><h2>沈妍没有来。</h2><p>你们约好今天中午见面。她没有出现，电话关机，微信也没有回复。</p><p>傍晚，你用她留给你的备用门锁密码进了公寓。屋里没人，电脑没有关机，微信和浏览器仍保持登录。</p><blockquote><b>徐宁　18:37</b>我去你家看看。看到回我。</blockquote><em>屋里很安静，电脑屏幕还亮着。</em><button onClick={()=>setIntro(false)}>查看电脑</button></section></div>}
  {app&&<Window title={appTitle} max={max} allowMax={app==="browser"||app==="verse"} close={()=>setApp(null)} toggle={()=>setMax(!max)}>{app==="browser"?<Browser privateUnlocked={privateUnlocked} setPrivateUnlocked={setPrivateUnlocked} onCopyMaterial={rememberMaterial} hasMaterial={id=>materials.some(m=>m.id===id)} initialPostId={wxPost} onInitialPostConsumed={()=>setWxPost(null)}/>:app==="wechat"?<InteractiveWechat materials={materials} onOpenPost={id=>{setWxPost(id);setApp("browser");setMax(true)}}/>:app==="notes"?<LocalVault unlocked={noteUnlocked} onUnlock={()=>setNoteUnlocked(true)} openLink={()=>open("verse")}/>:<VersePage onCopyMaterial={rememberMaterial} hasMaterial={id=>materials.some(m=>m.id===id)}/>}</Window>}
  <nav className="dock"><button onClick={()=>open("browser")}><i className="blue"><Globe2/></i></button><button onClick={()=>open("wechat")}><i className="green"><MessageCircle/>{!wxRead&&<b>1</b>}</i></button><button onClick={()=>open("notes")}><i className="amber"><NotebookPen/></i></button></nav>
 </main>
}
function Icon({label,tone,icon,badge,onClick}:{label:string;tone:string;icon:ReactNode;badge?:boolean;onClick:()=>void}){return <button className="desktop-icon" onClick={onClick}><i className={tone}>{icon}{badge&&<b>1</b>}</i><span>{label}</span></button>}
function Window({title,max,allowMax,close,toggle,children}:{title:string;max:boolean;allowMax:boolean;close:()=>void;toggle:()=>void;children:ReactNode}){return <section className={"window "+(max?"max":"float")}><header><div><button className="red" onClick={close}><X/></button><button className="yellow" onClick={close}><Minimize2/></button>{allowMax&&<button className="green-dot" onClick={toggle}><Maximize2/></button>}</div><b>{title}</b><span/></header>{children}</section>}

function Browser({privateUnlocked,setPrivateUnlocked,onCopyMaterial,hasMaterial,initialPostId,onInitialPostConsumed}:{privateUnlocked:boolean;setPrivateUnlocked:(value:boolean)=>void;onCopyMaterial:(m:SharedMaterial)=>void;hasMaterial:(id:string)=>boolean;initialPostId:string|null;onInitialPostConsumed:()=>void}){
 const [route,setRoute]=useState<Route>(initialPostId?{kind:"post",id:initialPostId}:{kind:"home"}),[stack,setStack]=useState<Route[]>([]),[q,setQ]=useState(""),[read,setRead]=useState<string[]>(initialPostId?[initialPostId]:[]);
 const [forumIdentity,setForumIdentity]=useState<"shenyan"|"admin">(()=>persistedForumIdentity);
 useEffect(()=>{if(initialPostId)onInitialPostConsumed()},[]);
 const go=(next:Route)=>{setStack([...stack,route]);setRoute(next);if(next.kind==="post")setRead([...new Set([...read,next.id])])};
 const back=()=>{if(forumIdentity==="admin"||!stack.length)return;setRoute(stack[stack.length-1]);setStack(stack.slice(0,-1))};
 const search=(value=q)=>{if(value.trim()){setQ(value);go({kind:"search",q:value.trim()})}};
 const openUser=(name:string)=>name==="候鸟第七年"?go({kind:"profile"}):go({kind:"user",name});
 return <div className="browser"><div className="tabs"><span>烛</span><b>烛阴旧闻</b></div><div className="bar"><button onClick={back}><ArrowLeft/></button><button onClick={()=>setRoute({...route})}><RefreshCw/></button><div><LockKeyhole/>www.zhuyinwen.cn / {forumIdentity==="admin"?"admin":route.kind}</div><button onClick={()=>forumIdentity==="shenyan"&&go({kind:"history"})}><HistoryIcon/></button></div>
  <div className="site">
   {forumIdentity==="admin"?<AdminPortal loggedIn={true} onAdminLogin={()=>{}} onCancel={()=>{}}/>:route.kind==="account"?<AdminPortal loggedIn={false} onCancel={back} onAdminLogin={()=>{persistedForumIdentity="admin";setForumIdentity("admin");setStack([])}}/>:<>
    <ForumHeader q={q} setQ={setQ} search={search} home={()=>go({kind:"home"})} me={()=>go({kind:"profile"})} switchAccount={()=>go({kind:"account"})}/>
    {route.kind==="home"&&<ForumHome read={read} open={id=>go({kind:"post",id})} me={()=>go({kind:"profile"})}/>} 
    {route.kind==="post"&&<Thread post={investigationPosts.find(x=>x.id===route.id)!} openUser={openUser} onCopyMaterial={onCopyMaterial} hasMaterial={hasMaterial}/>} 
    {route.kind==="profile"&&<Profile open={id=>go({kind:"post",id})} secret={()=>go({kind:"private"})}/>} 
    {route.kind==="user"&&<UserProfile name={route.name} open={id=>go({kind:"post",id})}/>} 
    {route.kind==="private"&&<PrivateArea entries={investigationPrivateEntries} unlocked={privateUnlocked} onUnlock={()=>setPrivateUnlocked(true)} onCopyMaterial={onCopyMaterial} hasMaterial={hasMaterial}/>} 
    {route.kind==="history"&&<HistoryPage open={id=>go({kind:"post",id})} me={()=>go({kind:"profile"})} search={search}/>} 
    {route.kind==="search"&&<Results q={route.q} read={read} open={id=>go({kind:"post",id})} openUser={openUser}/>} 
   </>}
  </div></div>
}
function ForumHeader({q,setQ,search,home,me,switchAccount}:{q:string;setQ:(x:string)=>void;search:(x?:string)=>void;home:()=>void;me:()=>void;switchAccount:()=>void}){return <><header className="forum-head"><button onClick={home} className="brand"><i>烛</i><span><b>烛阴旧闻</b><small>民俗 · 旧闻 · 城市记忆</small></span></button><div style={{display:"flex",alignItems:"center",gap:8}}><button onClick={me}><i className="bird">候</i><span><b>候鸟第七年</b><small>当前登录账号</small></span></button><button onClick={switchAccount} style={{height:34,padding:"0 10px",border:"1px solid #d8d3c8",borderRadius:6,background:"#f7f4ee",color:"#6b675f",fontSize:11}}>登录其他账号</button></div></header>
 <nav className="forum-nav"><button onClick={home}><Home/>论坛首页</button><button onClick={me}>我的主页</button></nav>
 <form className="forum-search" onSubmit={e=>{e.preventDefault();search()}}><span><Search/><b>全站搜索</b><small>站内主题与用户</small></span><label><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索帖子、用户或关键词"/><button>搜索</button></label></form></>}
function ForumHome({read,open,me}:{read:string[];open:(id:string)=>void;me:()=>void}){const [board,setBoard]=useState("全部");const visible=HOME_POST_IDS.map(pid=>investigationPosts.find(p=>p.id===pid)).filter((p):p is Post=>!!p);const shown=board==="全部"?visible:visible.filter(p=>p.board===board);return <main className="forum-page"><div className="columns"><section className="topics"><div className="boards">{["全部","闲聊灌水","旧闻考据","梦与睡眠","生活求助","站务区"].map(x=><button className={x===board?"active":""} onClick={()=>setBoard(x)} key={x}>{x}</button>)}</div><div className="notice"><b>站务</b><button onClick={()=>open("31002")}>旧帖合并、原链接与存档编号说明</button></div><header className="list-head"><b>最新 / 热门</b><span>{shown.length}个主题</span><span>回复 / 浏览</span></header>{shown.map(p=><Row key={p.id} p={p} read={read.includes(p.id)} open={()=>open(p.id)}/>)}</section><aside><button className="account" onClick={me}><i>候</i><b>候鸟第七年</b><small>上次活动：10月16日 19:48</small><dl><div><dt>主题</dt><dd>{profile.topics.length}</dd></div><div><dt>回复</dt><dd>47</dd></div><div><dt>收藏</dt><dd>12</dd></div></dl><span>查看个人主页</span></button><section className="side"><h3>旧档迁移</h3><p>2016 年前的主题已完成索引迁移，部分附件与楼层仍在恢复。</p></section></aside></div><footer>烛阴旧闻 · 建站于 2008 年 7 月 12 日 · 当前在线 127 人</footer></main>}
function Row({p,read,open}:{p:Post;read:boolean;open:()=>void}){return <button className={"row "+(read?"read":"")} onClick={open}><i>{p.board==="站务区"?"务":p.board==="旧闻考据"?"档":p.board==="梦与睡眠"?"梦":"帖"}</i><span><b>{p.title}</b><p>{p.excerpt}</p><small>{p.author} · {p.board} · {p.date}</small></span><em><b>{p.replies.length}</b><small>{p.views}</small></em></button>}
function Thread({post,openUser,onCopyMaterial,hasMaterial}:{post:Post;openUser:(name:string)=>void;onCopyMaterial:(m:SharedMaterial)=>void;hasMaterial:(id:string)=>boolean}){const [zoom,setZoom]=useState<{src:string;caption:string}|null>(null);const media=post.images||(post.image?[{src:post.image,caption:"附件：room_0617.jpg（凭记忆重画的第六版）"}]:[]);return <main className="thread"><div className="crumb">论坛首页 <ChevronRight/> {post.board} <ChevronRight/> #{post.id}</div><header className="thread-title"><span>{post.board}</span><h2>{post.title}</h2><p>楼主：<button className="author-link" onClick={()=>openUser(post.author)}><b>{post.author}</b></button>　发表于 {post.date}　浏览 {post.views}</p>{SHAREABLE_POST_IDS.has(post.id)&&<button disabled={hasMaterial(post.id)} onClick={()=>onCopyMaterial({id:post.id,title:post.title,kind:"论坛帖子",url:"https://www.zhuyinwen.cn/thread/"+post.id})} style={{marginTop:8,border:"1px solid #b8afa5",background:"#fff",borderRadius:5,padding:"6px 10px",fontSize:12,cursor:hasMaterial(post.id)?"default":"pointer",opacity:hasMaterial(post.id)?.55:1}}>{hasMaterial(post.id)?"已添加":"添加到材料"}</button>}</header><Floor user={post.author} time={post.date} no="楼主" role="楼主" openUser={openUser}><>{post.body.map((x,i)=><p key={i}><MarkedText text={x} marks={post.highlights}/></p>)}{!!media.length&&<div className="attachments">{media.map(x=><figure key={x.src}><button onClick={()=>setZoom(x)} title="点击查看原图"><img src={x.src} alt={x.caption}/><span><Maximize2/>查看原图</span></button><figcaption>{x.caption}</figcaption></figure>)}</div>}</></Floor>{post.replies.map((x,i)=><Floor key={i} user={x.user} time={x.time} no={(i+2)+"楼"} role={x.role} openUser={openUser}><MarkedText text={x.text} marks={post.highlights}/></Floor>)}{post.archive&&<div className="archive"><Clock3/><MarkedText text={post.archive} marks={post.highlights}/></div>}<div className="reply"><h3>回复主题</h3><p>该主题已归档，暂不开放回复。</p></div>{zoom&&<button className="lightbox" onClick={()=>setZoom(null)}><span><X/>关闭</span><img src={zoom.src} alt={zoom.caption}/><em>{zoom.caption}</em></button>}</main>}
function Floor({user,time,no,role,children,openUser}:{user:string;time:string;no:string;role?:string;children:ReactNode;openUser:(name:string)=>void}){return <article className="floor"><aside><i>{user[0]}</i><button className="author-link" onClick={()=>openUser(user)}><b>{user}</b></button>{role&&<em>{role}</em>}<small>注册用户</small></aside><section><header><span>{time}</span><b>{no}</b></header><div>{children}</div></section></article>}
function MarkedText({text,marks=[]}:{text:string;marks?:string[]}){const usable=marks.filter(Boolean).sort((a,b)=>b.length-a.length);if(!usable.length)return <>{text}</>;const escaped=usable.map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"));const parts=text.split(new RegExp(`(${escaped.join("|")})`,"g"));return <>{parts.map((part,i)=>usable.includes(part)?<strong className="clue" key={i}>{part}</strong>:part)}</>}
function Profile({open,secret}:{open:(id:string)=>void;secret:()=>void}){return <main className="profile"><header><i>候</i><span><h2>候鸟第七年</h2><p>偶尔失眠，拍旧楼。私信不看付费解梦。</p><small>注册于 2017-07-12 · 最后活动 2026-10-16 19:48 · 当前登录账号</small></span><dl><div><dt>主题</dt><dd>{profile.topics.length}</dd></div><div><dt>回复</dt><dd>47</dd></div><div><dt>收藏</dt><dd>12</dd></div></dl></header><div className="profile-grid"><section className="panel"><h3>公开主题（{profile.topics.length}） <small>按发布时间从早到晚</small></h3>{profile.topics.map(id=>{const p=investigationPosts.find(x=>x.id===id)!;return <button key={id} onClick={()=>open(id)}><span><b>{p.title}</b><small>{p.board} · {p.date}</small></span><ChevronRight/></button>})}</section><aside><button className="secret-card" onClick={secret}><LockKeyhole/><span><b>私密主题（{investigationPrivateEntries.length}）</b><small>仅自己可见</small></span><ChevronRight/></button></aside></div></main>}
function UserProfile({name,open}:{name:string;open:(id:string)=>void}){const rows=useMemo(()=>{const out:{id:string;kind:string;title:string;text:string;date:string}[]=[];investigationPosts.forEach(p=>{if(p.author===name)out.push({id:p.id,kind:"主题",title:p.title,text:p.excerpt,date:p.date});p.replies.forEach(r=>{if(r.user===name)out.push({id:p.id,kind:"回复",title:p.title,text:r.text,date:r.time})})});return out},[name]);return <main className="profile"><header><i>{name[0]}</i><span><h2>{name}</h2><p>公开账号资料</p><small>可查看仍保留在站内的公开主题与回复记录</small></span><dl><div><dt>可见记录</dt><dd>{rows.length}</dd></div></dl></header><section className="panel"><h3>公开发言记录</h3>{rows.length?rows.map((r,i)=><button key={r.id+"-"+i} onClick={()=>open(r.id)}><span><b>{r.kind} · {r.title}</b><small>{r.date}</small><p>{r.text}</p></span><ChevronRight/></button>):<div className="empty"><p>没有可见记录，或旧内容已无法通过该账号索引。</p></div>}</section></main>}
function HistoryPage({open,me,search}:{open:(id:string)=>void;me:()=>void;search:(q:string)=>void}){const natural=[history[0],{title:"河临明日天气",info:"天气 · 多云转小雨"},history[1],{title:"胶片冲洗店 营业时间",info:"本地生活 · 页面已关闭"},{title:"老电影里常见的红铁皮盒是哪家出的",info:"烛阴旧闻 · #30177",id:"30177"},{title:"睡眠门诊 反复梦境",info:"澄川搜索 · 10月12日"},{title:"旧帖合并、原链接与存档编号说明",info:"烛阴旧闻 · #31002",id:"31002"},{title:"旧单位房 厨房门 朝走廊",info:"图片搜索 · 页面已关闭"}];return <main className="history"><header><HistoryIcon/><span><h2>浏览记录</h2><p>沈妍的本地记录</p></span></header><section>{natural.map((x:any,i)=><button key={i} onClick={()=>x.id?open(x.id):x.profile?me():x.query?search(x.query):undefined}><time>{i<4?"昨天":"10月15日"}</time><span><b>{x.title}</b><small>{x.info}</small></span><ChevronRight/></button>)}</section></main>}
function Results({q,read,open,openUser}:{q:string;read:string[];open:(id:string)=>void;openUser:(name:string)=>void}){const n=norm(q);const found=useMemo(()=>{const tokens=q.split(/\s+/).map(norm).filter(Boolean);return investigationPosts.filter(p=>{const hay=norm([p.title,p.author,p.excerpt,...p.body,...(p.terms||[]),p.archive||"",...p.replies.flatMap(r=>[r.user,r.text])].join(" "));return tokens.every(token=>hay.includes(token))||n===p.id})},[q,n]);const users=useMemo(()=>{const names=new Set<string>();investigationPosts.forEach(p=>{names.add(p.author);p.replies.forEach(r=>names.add(r.user))});return [...names].filter(name=>norm(name).includes(n)).slice(0,2)},[n]);return <main className="results"><header><Search/><span><h2>搜索“{q}”</h2><p>公开主题 {found.length} 条{users.length?`，用户 ${users.length} 条`:""}</p></span></header><section>{users.map(name=><button className="user-result" onClick={()=>openUser(name)} key={name}><i>{name[0]}</i><span><b>用户：{name}</b><small>查看公开主题与回复历史</small></span><ChevronRight/></button>)}{found.map(p=><Row key={p.id} p={p} read={read.includes(p.id)} open={()=>open(p.id)}/>)}{!found.length&&!users.length&&<div className="empty"><Search/><h3>没有找到匹配的公开内容</h3></div>}</section></main>}
const norm=(x:string)=>x.toLowerCase().replace(/[“”‘’#，。！？、\s]/g,"");

function VersePage({onCopyMaterial,hasMaterial}:{onCopyMaterial:(m:SharedMaterial)=>void;hasMaterial:(id:string)=>boolean}){const added=hasMaterial("verse");return <main className="verse-page"><header><LockKeyhole/><span>www.zhuyinwen.cn/archive/cache/baishesong-1986.html</span><b>缓存页面</b></header><section className="verse-image-view simple"><figure><img src="assets/baishesong-recovered-scan-v1.webp" alt="一张来源不明的黑纸红字抄写页扫描件"/><figcaption><span>scan_07_untitled.tif</span><em>来源字段已删除 · 缓存于 2026-10-16 19:49</em></figcaption></figure><article style={{maxWidth:720,margin:"18px auto 0",padding:"16px 18px",background:"#f5f1e9",border:"1px solid #d7cec1",lineHeight:1.8,fontSize:14}}><small style={{color:"#8a8179"}}>缓存页附带的手工抄录</small><p>能辨认的其中一句是：<strong className="clue">身非我身，名非我名</strong>。标点为后补，原页只有连续八字。</p><button disabled={added} onClick={()=>onCopyMaterial({id:"verse",title:"身非我身，名非我名",kind:"手工抄录",url:"https://www.zhuyinwen.cn/archive/cache/baishesong-1986.html"})} style={{border:"1px solid #b8afa5",background:"#fff",borderRadius:5,padding:"7px 10px",fontSize:12,cursor:"pointer"}}>{added?"已添加":"添加到材料"}</button></article></section></main>}
