"use client";
/* eslint-disable @next/next/no-img-element */
// v9.2.3 Zhou identity discovery
import {ReactNode,useEffect,useMemo,useState} from "react";
import {ArrowLeft,ChevronRight,Clock3,FilePlus2,Globe2,History as HistoryIcon,Home,LockKeyhole,Maximize2,MessageCircle,Minimize2,NotebookPen,RefreshCw,Search,Wifi,X} from "lucide-react";
import {history,Post,posts,privateEntries,profile} from "../content/gameDataFlowV2";
import {applyForumPost,applyPrivateEntry} from "../content/forumDialogues";
import LocalVault from "./LocalVault";
import InteractiveWechat,{SharedMaterial,WechatNotice,discoverZhouIdentity,focusWechatContact,subscribeWechatNotices} from "./InteractiveWechat";
import PrivateArea from "./PrivateArea";
import AdminPortalOccult from "./AdminPortalOccult";
import {advanceGameClock,getGameClock,subscribeGameClock} from "./gameClock";
import GameEnding from "./GameEnding";
import {getEnding,subscribeEnding} from "./endingState";

type App="browser"|"wechat"|"notes"|"verse";
type Route={kind:"home"}|{kind:"post",id:string}|{kind:"profile"}|{kind:"user",name:string}|{kind:"private"}|{kind:"history"}|{kind:"search",q:string}|{kind:"account"};

const contextPosts:Post[]=[];
const investigationPosts=posts.map(applyForumPost);
const investigationPrivateEntries=privateEntries.map(applyPrivateEntry);
const SHAREABLE_POST_IDS=new Set(["33897","09114","09831","14692","17428","11208","23109","27614"]);
const HOME_POST_IDS=["31003","34106","34091","34086","34080","34064","34055","34049","20847","34043","33992","33981"];
let persistedForumIdentity:"shenyan"|"admin"="shenyan";
let persistedForumRead:string[]=[];
let persistedForumRoute:Route={kind:"home"};
let persistedForumStack:Route[]=[];
let persistedForumQ="";

export default function Page(){
 const [stage,setStage]=useState<"title"|"login"|"desktop">("title");
 const [intro,setIntro]=useState(true),[app,setApp]=useState<App|null>(null),[max,setMax]=useState(true),[wxRead,setWxRead]=useState(false),[privateUnlocked,setPrivateUnlocked]=useState(false),[noteUnlocked,setNoteUnlocked]=useState(false);
 const [materials,setMaterials]=useState<SharedMaterial[]>([]);
 const [verseSeen,setVerseSeen]=useState(false);
 const [wxPost,setWxPost]=useState<string|null>(null);
 const [wxNotices,setWxNotices]=useState<(WechatNotice&{id:number})[]>([]);
 const [clock,setClock]=useState(()=>getGameClock());
 const [ending,setEnding]=useState(()=>getEnding());
 useEffect(()=>subscribeGameClock(setClock),[]);
 useEffect(()=>subscribeEnding(setEnding),[]);
 const rememberMaterial=(m:SharedMaterial)=>setMaterials(prev=>prev.some(x=>x.id===m.id)?prev:[...prev,m]);
 useEffect(()=>subscribeWechatNotices(notice=>{
  const item={...notice,id:Date.now()+Math.floor(Math.random()*1000)};
  setWxRead(false);
  setWxNotices(prev=>[...prev.filter(x=>x.contactId!==notice.contactId),item].slice(-3));
  window.setTimeout(()=>setWxNotices(prev=>prev.filter(x=>x.id!==item.id)),12000);
 }),[app]);
 if(ending)return <GameEnding kind={ending}/>;
 if(stage==="title")return <main className="title"><section><small>河临 · 2026年10月17日</small><h1>烛阴旧闻</h1><p>沈妍没有赴约。<br/>电话关机，消息也没有回复。</p><button onClick={()=>setStage("login")}>进入公寓 <ChevronRight/></button></section></main>;
 if(stage==="login")return <main className="login"><div className="clock"><b>19:06</b><span>10月17日　星期六</span></div><section><div className="avatar">妍</div><h2>沈妍</h2><button className="password" onClick={()=>setStage("desktop")}><span>••••••••</span><ChevronRight/></button><p>你和沈妍从小学低年级就认识。你们互为紧急联系人，也一直留着彼此的备用门锁密码。</p></section></main>;
 const open=(x:App)=>{advanceGameClock(1);setApp(x);setMax(x==="browser"||x==="verse");if(x==="wechat")setWxRead(true)};
 const appTitle=app==="browser"?"澄川浏览器":app==="wechat"?"微信":app==="notes"?"本地资料":app==="verse"?"澄川浏览器":"访达";
 return <main className="desktop"><header className="sys"><div><b>●</b><strong>{appTitle}</strong><span>文件</span><span>编辑</span></div><div><Wifi/><span>80%</span><span>10月17日 周六 {clock}</span></div></header>
  <div className="shortcuts"><Icon label="浏览器" tone="blue" icon={<Globe2/>} onClick={()=>open("browser")}/><Icon label="微信" tone="green" icon={<MessageCircle/>} badge={!wxRead} onClick={()=>open("wechat")}/><Icon label="本地资料" tone="amber" icon={<NotebookPen/>} onClick={()=>open("notes")}/></div>
  {intro&&<div className="overlay"><section className="intro"><small><Clock3/> 2026年10月17日　19:06</small><h2>沈妍没有来。</h2><p>你们约好今天中午见面。她没有出现，电话关机，微信也没有回复。</p><p>傍晚，你用她留给你的备用门锁密码进了公寓。屋里没人，电脑没有关机，微信和浏览器仍保持登录。</p><blockquote><b>徐宁　18:37</b>我去你家看看。看到回我。</blockquote><em>屋里很安静，电脑屏幕还亮着。</em><button onClick={()=>setIntro(false)}>查看电脑</button></section></div>}
  {app&&<Window title={appTitle} max={max} allowMax={app==="browser"||app==="verse"} close={()=>setApp(null)} toggle={()=>setMax(!max)}>{app==="browser"?<Browser privateUnlocked={privateUnlocked} setPrivateUnlocked={setPrivateUnlocked} onCopyMaterial={rememberMaterial} hasMaterial={id=>materials.some(m=>m.id===id)} verseSeen={verseSeen} initialPostId={wxPost} onInitialPostConsumed={()=>setWxPost(null)}/>:app==="wechat"?<InteractiveWechat materials={materials} onOpenPost={id=>{setWxPost(id);setApp("browser");setMax(true)}}/>:app==="notes"?<LocalVault unlocked={noteUnlocked} onUnlock={()=>setNoteUnlocked(true)} openLink={()=>{setVerseSeen(true);open("verse")}}/>:<VersePage onCopyMaterial={rememberMaterial} hasMaterial={id=>materials.some(m=>m.id===id)}/>}</Window>}
  {!!wxNotices.length&&<div style={{position:"fixed",right:18,top:38,zIndex:80,width:350,display:"grid",gap:8}}>{wxNotices.map(n=><button key={n.id} onClick={()=>{focusWechatContact(n.contactId);setWxNotices(prev=>prev.filter(x=>x.contactId!==n.contactId));open("wechat")}} style={{display:"grid",gridTemplateColumns:"38px 1fr",gap:10,alignItems:"center",padding:"13px 14px",border:"2px solid #42a967",borderRadius:10,background:"#fff",boxShadow:"0 14px 38px #0005",textAlign:"left",cursor:"pointer"}}><i style={{width:36,height:36,display:"grid",placeItems:"center",borderRadius:9,background:"#2bbd60",color:"#fff",fontStyle:"normal"}}><MessageCircle size={19}/></i><span style={{minWidth:0}}><b style={{display:"block",fontSize:12}}><span style={{marginRight:6,color:"#2a9f55"}}>新消息</span>微信 · {n.name}</b><small style={{display:"block",marginTop:3,color:"#666",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{n.text}</small></span></button>)}</div>}
  <nav className="dock"><button onClick={()=>open("browser")}><i className="blue"><Globe2/></i></button><button onClick={()=>open("wechat")}><i className="green"><MessageCircle/>{!wxRead&&<b>1</b>}</i></button><button onClick={()=>open("notes")}><i className="amber"><NotebookPen/></i></button></nav>
 </main>
}
function Icon({label,tone,icon,badge,onClick}:{label:string;tone:string;icon:ReactNode;badge?:boolean;onClick:()=>void}){return <button className="desktop-icon" onClick={onClick}><i className={tone}>{icon}{badge&&<b>1</b>}</i><span>{label}</span></button>}
function Window({title,max,allowMax,close,toggle,children}:{title:string;max:boolean;allowMax:boolean;close:()=>void;toggle:()=>void;children:ReactNode}){return <section className={"window "+(max?"max":"float")}><header><div><button className="red" onClick={close}><X/></button><button className="yellow" onClick={close}><Minimize2/></button>{allowMax&&<button className="green-dot" onClick={toggle}><Maximize2/></button>}</div><b>{title}</b><span/></header>{children}</section>}

function Browser({privateUnlocked,setPrivateUnlocked,onCopyMaterial,hasMaterial,verseSeen,initialPostId,onInitialPostConsumed}:{privateUnlocked:boolean;setPrivateUnlocked:(value:boolean)=>void;onCopyMaterial:(m:SharedMaterial)=>void;hasMaterial:(id:string)=>boolean;verseSeen:boolean;initialPostId:string|null;onInitialPostConsumed:()=>void}){
 const [route,setRoute]=useState<Route>(()=>initialPostId?{kind:"post",id:initialPostId}:persistedForumRoute),[stack,setStack]=useState<Route[]>(()=>initialPostId?[...persistedForumStack,persistedForumRoute]:persistedForumStack),[q,setQ]=useState(()=>persistedForumQ),[read,setRead]=useState<string[]>(()=>[...new Set([...persistedForumRead,...(initialPostId?[initialPostId]:[])])]);
 const [forumIdentity,setForumIdentity]=useState<"shenyan"|"admin">(()=>persistedForumIdentity);
 useEffect(()=>{if(initialPostId)onInitialPostConsumed()},[]);
 useEffect(()=>{persistedForumRoute=route;persistedForumStack=stack;persistedForumQ=q},[route,stack,q]);
 const go=(next:Route)=>{advanceGameClock(1);setStack([...stack,route]);setRoute(next);if(next.kind==="post"){const nextRead=[...new Set([...read,next.id])];persistedForumRead=nextRead;setRead(nextRead)}};
 const back=()=>{if(forumIdentity==="admin"||!stack.length)return;setRoute(stack[stack.length-1]);setStack(stack.slice(0,-1))};
 const search=(value=q)=>{if(value.trim()){const term=value.trim();setQ(value);if(term==="折柳"){go({kind:"user",name:"折柳"});return}go({kind:"search",q:term})}};
 const openUser=(name:string)=>name==="候鸟第七年"?go({kind:"profile"}):go({kind:"user",name});
 return <div className="browser"><div className="tabs"><span>{forumIdentity==="admin"?"档":"烛"}</span><b>{forumIdentity==="admin"?"内部资料库":"烛阴旧闻"}</b></div><div className="bar"><button onClick={back}><ArrowLeft/></button><button onClick={()=>setRoute({...route})}><RefreshCw/></button><div><LockKeyhole/>www.zhuyinwen.cn / {forumIdentity==="admin"?"admin":route.kind}</div>{forumIdentity==="admin"?<button onClick={()=>{persistedForumIdentity="shenyan";setForumIdentity("shenyan");setRoute({kind:"home"});setStack([])}} style={{width:"auto",padding:"0 10px",fontSize:11}}>返回论坛</button>:<button onClick={()=>go({kind:"history"})}><HistoryIcon/></button>}</div>
  <div className="site">
   {forumIdentity==="admin"?<AdminPortalOccult loggedIn={true} canUseLegacy={true} onAdminLogin={()=>{}} onCancel={()=>{}} onExitAdmin={()=>{persistedForumIdentity="shenyan";setForumIdentity("shenyan");setRoute({kind:"home"});setStack([])}} onWechatIncoming={()=>setWxRead(false)} onCopyMaterial={onCopyMaterial} hasMaterial={hasMaterial}/>:route.kind==="account"?<AdminPortalOccult loggedIn={false} canUseLegacy={verseSeen} onCancel={back} onAdminLogin={()=>{persistedForumIdentity="admin";setForumIdentity("admin");setStack([])}} onWechatIncoming={()=>setWxRead(false)} onCopyMaterial={onCopyMaterial} hasMaterial={hasMaterial}/>:<>
    <ForumHeader q={q} setQ={setQ} search={search} home={()=>go({kind:"home"})} me={()=>go({kind:"profile"})} switchAccount={()=>go({kind:"account"})}/>
    {route.kind==="home"&&<ForumHome read={read} open={id=>go({kind:"post",id})} me={()=>go({kind:"profile"})}/>} 
    {route.kind==="post"&&<Thread post={investigationPosts.find(x=>x.id===route.id)!} openUser={openUser} onCopyMaterial={onCopyMaterial} hasMaterial={hasMaterial}/>} 
    {route.kind==="profile"&&<Profile open={id=>go({kind:"post",id})} secret={()=>go({kind:"private"})}/>} 
    {route.kind==="user"&&(route.name==="折柳"?<ZheliuProfile open={id=>go({kind:"post",id})}/>:<UserProfile name={route.name} open={id=>go({kind:"post",id})}/>)} 
    {route.kind==="private"&&<PrivateArea entries={investigationPrivateEntries} unlocked={privateUnlocked} onUnlock={()=>setPrivateUnlocked(true)} onCopyMaterial={onCopyMaterial} hasMaterial={hasMaterial}/>} 
    {route.kind==="history"&&<HistoryPage open={id=>go({kind:"post",id})} me={()=>go({kind:"profile"})} search={search}/>} 
    {route.kind==="search"&&<Results q={route.q} read={read} open={id=>go({kind:"post",id})} openUser={openUser}/>} 
   </>}
  </div></div>
}
function ZheliuProfile({open}:{open:(id:string)=>void}){
 useEffect(()=>{discoverZhouIdentity()},[]);
 return <main className="forum-page"><section style={{maxWidth:760,margin:"0 auto",padding:"22px 24px",border:"1px solid #ddd6ca",borderRadius:8,background:"#fbfaf6"}}><div style={{display:"flex",alignItems:"center",gap:14,paddingBottom:16,borderBottom:"1px solid #e4dfd5"}}><i style={{width:46,height:46,display:"grid",placeItems:"center",borderRadius:"50%",background:"#e8e3d8",fontStyle:"normal",fontWeight:800}}>折</i><span><h2 style={{margin:"0 0 5px",fontSize:20}}>折柳</h2><b style={{display:"block",fontSize:13}}>实名资料：周川</b><small style={{display:"block",marginTop:4,color:"#888"}}>公开资料页 · 烛阴旧闻用户</small></span></div><div style={{padding:"16px 0 4px",fontSize:13,lineHeight:1.8}}><p style={{margin:"0 0 10px"}}>个人资料很少，只保留了实名验证字段和公开回复记录。</p><button onClick={()=>open("20847")} style={{width:"100%",padding:"11px 12px",border:"1px solid #d8d2c7",borderRadius:6,background:"#fff",textAlign:"left",cursor:"pointer"}}><b style={{display:"block"}}>最近公开回复</b><small style={{display:"block",marginTop:4,color:"#777"}}>候鸟第七年的梦帖 · “看完了。红盒子先别管……”</small></button></div></section></main>
}

function ForumHeader({q,setQ,search,home,me,switchAccount}:{q:string;setQ:(x:string)=>void;search:(x?:string)=>void;home:()=>void;me:()=>void;switchAccount:()=>void}){return <><header className="forum-head"><button onClick={home} className="brand"><i>烛</i><span><b>烛阴旧闻</b><small>民俗 · 旧闻 · 城市记忆</small></span></button><div style={{display:"flex",alignItems:"center",gap:8}}><button onClick={me}><i className="bird">候</i><span><b>候鸟第七年</b><small>当前登录账号</small></span></button><button onClick={switchAccount} style={{height:34,padding:"0 10px",border:"1px solid #d8d3c8",borderRadius:6,background:"#f7f4ee",color:"#6b675f",fontSize:11}}>登录其他账号</button></div></header>
 <nav className="forum-nav"><button onClick={home}><Home/>论坛首页</button><button onClick={me}>我的主页</button></nav>
 <form className="forum-search" onSubmit={e=>{e.preventDefault();search()}}><span><Search/><b>全站搜索</b><small>站内主题与用户</small></span><label><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索帖子、用户或关键词"/><button>搜索</button></label></form></>}
function ForumHome({read,open,me}:{read:string[];open:(id:string)=>void;me:()=>void}){const [board,setBoard]=useState("全部");const visible=HOME_POST_IDS.map(pid=>investigationPosts.find(p=>p.id===pid)).filter((p):p is Post=>!!p);const shown=board==="全部"?visible:visible.filter(p=>p.board===board);return <main className="forum-page"><div className="columns"><section className="topics"><div className="boards">{["全部","闲聊灌水","旧闻考据","梦与睡眠","生活求助","站务区"].map(x=><button className={x===board?"active":""} onClick={()=>setBoard(x)} key={x}>{x}</button>)}</div><div className="notice"><b>站务</b><button onClick={()=>open("31002")}>旧帖合并、原链接与存档编号说明</button></div><header className="list-head"><b>最新 / 热门</b><span>{shown.length}个主题</span><span>回复 / 浏览</span></header>{shown.map(p=><Row key={p.id} p={p} read={read.includes(p.id)} open={()=>open(p.id)}/>)}</section><aside><button className="account" onClick={me}><i>候</i><b>候鸟第七年</b><small>上次活动：10月16日 19:48</small><dl><div><dt>主题</dt><dd>{profile.topics.length}</dd></div><div><dt>回复</dt><dd>47</dd></div><div><dt>收藏</dt><dd>12</dd></div></dl><span>查看个人主页</span></button><section className="side"><h3>旧档迁移</h3><p>2016 年前的主题已完成索引迁移，部分附件与楼层仍在恢复。</p></section></aside></div><footer>烛阴旧闻 · 建站于 2008 年 7 月 12 日 · 当前在线 127 人</footer></main>}
function Row({p,read,open}:{p:Post;read:boolean;open:()=>void}){return <button className={"row "+(read?"read":"")} onClick={open}><i>{p.board==="站务区"?"务":p.board==="旧闻考据"?"档":p.board==="梦与睡眠"?"梦":"帖"}</i><span><b>{p.title}</b><p>{p.excerpt}</p><small>{p.author} · {p.board} · {p.date}</small></span><em><b>{p.replies.length}</b><small>{p.views}</small></em></button>}
function Thread({post,openUser,onCopyMaterial,hasMaterial}:{post:Post;openUser:(name:string)=>void;onCopyMaterial:(m:SharedMaterial)=>void;hasMaterial:(id:string)=>boolean}){const [zoom,setZoom]=useState<{src:string;caption:string}|null>(null);const media=post.images||(post.image?[{src:post.image,caption:"附件：room_0617.jpg（凭记忆重画的第六版）"}]:[]);return <main className="thread"><div className="crumb">论坛首页 <ChevronRight/> {post.board} <ChevronRight/> #{post.id}</div><header className="thread-title"><span>{post.board}</span><h2>{post.title}</h2><p>楼主：<button className="author-link" onClick={()=>openUser(post.author)}><b>{post.author}</b></button>　发表于 {post.date}　浏览 {post.views}</p>{SHAREABLE_POST_IDS.has(post.id)&&<button disabled={hasMaterial(post.id)} onClick={()=>onCopyMaterial({id:post.id,title:post.title,kind:"论坛帖子",url:"https://www.zhuyinwen.cn/thread/"+post.id})} style={{minHeight:46,display:"inline-flex",alignItems:"center",justifyContent:"center",gap:9,marginTop:12,padding:"0 17px",border:hasMaterial(post.id)?"1px solid #bdc8c2":"2px solid #477563",background:hasMaterial(post.id)?"#eef1ef":"#e2f0e8",color:hasMaterial(post.id)?"#748079":"#285943",borderRadius:8,fontSize:13,fontWeight:800,cursor:hasMaterial(post.id)?"default":"pointer",boxShadow:hasMaterial(post.id)?"none":"0 7px 18px #274b3a24"}}><FilePlus2 size={18}/><span>{hasMaterial(post.id)?"已加入调查材料":"添加到调查材料"}</span></button>}</header><Floor user={post.author} time={post.date} no="楼主" role="楼主" openUser={openUser}><>{post.body.map((x,i)=><p key={i}><MarkedText text={x} marks={post.highlights}/></p>)}{!!media.length&&<div className="attachments">{media.map(x=><figure key={x.src}><button onClick={()=>setZoom(x)} title="点击查看原图"><img src={x.src} alt={x.caption}/><span><Maximize2/>查看原图</span></button><figcaption>{x.caption}</figcaption></figure>)}</div>}{post.id==="23109"&&<RecoveredRitualAttachment/>}</></Floor>{post.replies.map((x,i)=><Floor key={i} user={x.user} time={x.time} no={(i+2)+"楼"} role={x.role} openUser={openUser}><MarkedText text={x.text} marks={post.highlights}/></Floor>)}{post.archive&&<div className="archive"><Clock3/><MarkedText text={post.archive} marks={post.highlights}/></div>}<div className="reply"><h3>回复主题</h3><p>该主题已归档，暂不开放回复。</p></div>{zoom&&<button className="lightbox" onClick={()=>setZoom(null)}><span><X/>关闭</span><img src={zoom.src} alt={zoom.caption}/><em>{zoom.caption}</em></button>}</main>}
function RecoveredRitualAttachment(){
 const [phase,setPhase]=useState<"closed"|"error"|"open">("closed");
 if(phase==="closed")return <section style={{margin:"18px 0",width:"min(620px,100%)",boxSizing:"border-box",padding:16,border:"1px solid #d5cabc",background:"#f2ede4"}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:5}}><b style={{fontSize:13}}>失效附件</b><em style={{padding:"2px 6px",borderRadius:4,background:"#ead8d3",color:"#8d3e35",fontSize:10,fontStyle:"normal"}}>恢复失败</em></div><small style={{display:"block",margin:"0 0 12px",color:"#81766d"}}>thumb_2012_0712.jpg</small><button onClick={()=>setPhase("error")} style={{padding:"7px 11px",border:"1px solid #b8afa5",background:"#fff",borderRadius:5}}>打开附件</button></section>;
 if(phase==="error")return <button onClick={()=>setPhase("open")} style={{width:"min(620px,100%)",height:210,margin:"18px 0",display:"block",boxSizing:"border-box",border:"1px solid #341312",background:"#050505",color:"#7d1716",font:"700 28px serif",letterSpacing:".28em"}}>门未闭。<small style={{display:"block",marginTop:20,color:"#655a56",font:"11px sans-serif",letterSpacing:0}}>缓存读取失败 · 点击重试</small></button>;
 return <section style={{margin:"18px 0",width:"min(620px,100%)",boxSizing:"border-box",display:"grid",gap:12}}>
  <figure style={{margin:0,padding:10,boxSizing:"border-box",overflow:"hidden",border:"1px solid #2b2420",background:"#100d0c"}}><img src="assets/occult/recovered-ritual-v904.webp" alt="恢复出的旧仪式现场照片" style={{display:"block",width:"100%",background:"#080706"}}/><figcaption style={{padding:"9px 2px 1px",color:"#9d8f86",fontSize:11}}>恢复帧 01　原图缺损，色彩已严重偏移</figcaption></figure>
  <figure style={{margin:0,padding:10,boxSizing:"border-box",overflow:"hidden",border:"1px solid #2b2420",background:"#100d0c"}}><img src="assets/occult/recovered-talisman-v904.webp" alt="恢复出的黄纸局部" style={{display:"block",width:"100%",maxHeight:420,objectFit:"contain",background:"#080706"}}/><figcaption style={{padding:"9px 2px 1px",color:"#9d8f86",fontSize:11}}>恢复帧 02　黄纸局部裁切</figcaption></figure>
 </section>;
}
function Floor({user,time,no,role,children,openUser}:{user:string;time:string;no:string;role?:string;children:ReactNode;openUser:(name:string)=>void}){return <article className="floor"><aside><i>{user[0]}</i><button className="author-link" onClick={()=>openUser(user)}><b>{user}</b></button>{role&&<em>{role}</em>}<small>注册用户</small></aside><section><header><span>{time}</span><b>{no}</b></header><div>{children}</div></section></article>}
function MarkedText({text,marks=[]}:{text:string;marks?:string[]}){const usable=marks.filter(Boolean).sort((a,b)=>b.length-a.length);if(!usable.length)return <>{text}</>;const escaped=usable.map(x=>x.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"));const parts=text.split(new RegExp(`(${escaped.join("|")})`,"g"));return <>{parts.map((part,i)=>usable.includes(part)?<strong className="clue" key={i}>{part}</strong>:part)}</>}
function Profile({open,secret}:{open:(id:string)=>void;secret:()=>void}){return <main className="profile"><header><i>候</i><span><h2>候鸟第七年</h2><p>偶尔失眠，拍旧楼。私信不看付费解梦。</p><small>注册于 2017-07-12 · 最后活动 2026-10-16 19:48 · 当前登录账号</small></span><dl><div><dt>主题</dt><dd>{profile.topics.length}</dd></div><div><dt>回复</dt><dd>47</dd></div><div><dt>收藏</dt><dd>12</dd></div></dl></header><div className="profile-grid"><section className="panel"><h3>公开主题（{profile.topics.length}） <small>按发布时间从早到晚</small></h3>{profile.topics.map(id=>{const p=investigationPosts.find(x=>x.id===id)!;return <button key={id} onClick={()=>open(id)}><span><b>{p.title}</b><small>{p.board} · {p.date}</small></span><ChevronRight/></button>})}</section><aside><button className="secret-card" onClick={secret}><LockKeyhole/><span><b>私密主题（{investigationPrivateEntries.length}）</b><small>仅自己可见</small></span><ChevronRight/></button></aside></div></main>}
function UserProfile({name,open}:{name:string;open:(id:string)=>void}){const rows=useMemo(()=>{const out:{id:string;kind:string;title:string;text:string;date:string}[]=[];investigationPosts.forEach(p=>{if(p.author===name)out.push({id:p.id,kind:"主题",title:p.title,text:p.excerpt,date:p.date});p.replies.forEach(r=>{if(r.user===name)out.push({id:p.id,kind:"回复",title:p.title,text:r.text,date:r.time})})});return out},[name]);return <main className="profile"><header><i>{name[0]}</i><span><h2>{name}</h2><p>公开账号资料</p><small>可查看仍保留在站内的公开主题与回复记录</small></span><dl><div><dt>可见记录</dt><dd>{rows.length}</dd></div></dl></header><section className="panel"><h3>公开发言记录</h3>{rows.length?rows.map((r,i)=><button key={r.id+"-"+i} onClick={()=>open(r.id)}><span><b>{r.kind} · {r.title}</b><small>{r.date}</small><p>{r.text}</p></span><ChevronRight/></button>):<div className="empty"><p>没有可见记录，或旧内容已无法通过该账号索引。</p></div>}</section></main>}
function HistoryPage({open,me,search}:{open:(id:string)=>void;me:()=>void;search:(q:string)=>void}){const natural=[history[0],{title:"河临明日天气",info:"天气 · 多云转小雨"},history[1],{title:"胶片冲洗店 营业时间",info:"本地生活 · 页面已关闭"},{title:"老电影里常见的红铁皮盒是哪家出的",info:"烛阴旧闻 · #30177",id:"30177"},{title:"睡眠门诊 反复梦境",info:"澄川搜索 · 10月12日"},{title:"旧帖合并、原链接与存档编号说明",info:"烛阴旧闻 · #31002",id:"31002"},{title:"旧单位房 厨房门 朝走廊",info:"图片搜索 · 页面已关闭"}];return <main className="history"><header><HistoryIcon/><span><h2>浏览记录</h2><p>沈妍的本地记录</p></span></header><section>{natural.map((x:any,i)=><button key={i} onClick={()=>x.id?open(x.id):x.profile?me():x.query?search(x.query):undefined}><time>{i<4?"昨天":"10月15日"}</time><span><b>{x.title}</b><small>{x.info}</small></span><ChevronRight/></button>)}</section></main>}
function Results({q,read,open,openUser}:{q:string;read:string[];open:(id:string)=>void;openUser:(name:string)=>void}){const n=norm(q);const users=useMemo(()=>{const names=new Set<string>();investigationPosts.forEach(p=>{names.add(p.author);p.replies.forEach(r=>names.add(r.user))});return [...names].filter(name=>norm(name).includes(n)).slice(0,2)},[n]);const exactUser=useMemo(()=>users.find(name=>norm(name)===n),[users,n]);const found=useMemo(()=>{const tokens=q.split(/\s+/).map(norm).filter(Boolean);return investigationPosts.filter(p=>{if(n===p.id)return true;const directHay=norm([p.title,p.author,p.excerpt,...p.body,...(p.terms||[]),p.archive||"",...p.replies.map(r=>r.text)].join(" "));if(exactUser){return norm(p.author)===n||tokens.every(token=>directHay.includes(token));}const broadHay=norm([directHay,...p.replies.map(r=>r.user)].join(" "));return tokens.every(token=>broadHay.includes(token))})},[q,n,exactUser]);return <main className="results"><header><Search/><span><h2>搜索“{q}”</h2><p>公开主题 {found.length} 条{users.length?`，用户 ${users.length} 条`:""}</p></span></header><section>{users.map(name=><button className="user-result" onClick={()=>openUser(name)} key={name}><i>{name[0]}</i><span><b>用户：{name}</b><small>查看公开主题与回复历史</small></span><ChevronRight/></button>)}{found.map(p=><Row key={p.id} p={p} read={read.includes(p.id)} open={()=>open(p.id)}/>)}{!found.length&&!users.length&&<div className="empty"><Search/><h3>没有找到匹配的公开内容</h3></div>}</section></main>}
const norm=(x:string)=>x.toLowerCase().replace(/[“”‘’#，。！？、\s]/g,"");

function VersePage({onCopyMaterial,hasMaterial}:{onCopyMaterial:(m:SharedMaterial)=>void;hasMaterial:(id:string)=>boolean}){const added=hasMaterial("verse");return <main className="verse-page" style={{height:"100%",minHeight:"100%",overflowY:"auto",background:"#080606",color:"#ddd0c1"}}><header style={{borderBottom:"1px solid #2e1715",background:"#0d0b0a"}}><LockKeyhole/><span>www.zhuyinwen.cn/archive/cache/baishesong-1986.html</span><b>缓存页面</b></header><section style={{maxWidth:1040,margin:"0 auto",padding:"28px 30px 110px"}}><figure style={{width:"min(720px,100%)",margin:"0 auto",padding:10,background:"#080606",border:"1px solid #321714",boxShadow:"0 24px 80px #000",textAlign:"center"}}><img src="assets/occult/huanzhen-scripture-v904.webp" alt="无相还真黑底朱字旧教页" style={{display:"block",width:"100%",maxHeight:520,objectFit:"contain",objectPosition:"center top"}}/><figcaption style={{padding:"12px 12px 4px",color:"#75645c",fontSize:11}}>scan_07_untitled.tif · 来源字段已删除 · 缓存于 2026-10-16 19:49</figcaption></figure><article style={{maxWidth:720,margin:"18px auto 0",padding:"24px 24px 42px",border:"1px solid #3c1c18",background:"#120c0b",font:"15px serif",lineHeight:2,color:"#d8c4b1",overflow:"visible"}}><small style={{color:"#8d514a",letterSpacing:".14em"}}>恢复文字层</small><h2 style={{margin:"8px 0 16px",color:"#a82e28",font:"700 28px serif",letterSpacing:".12em"}}>无相还真</h2><p>无相还真，<strong style={{color:"#bd4b42"}}>舍身无量。</strong></p><p>赤烛引客，黄符镇舍。</p><p>旧客退位，新客安门。</p><p style={{marginTop:22,fontSize:20,letterSpacing:".12em"}}><strong style={{color:"#c04b43"}}>身非我身，名非我名。</strong></p><p style={{color:"#77645c",fontSize:12}}>页脚残留同一句祝号，重复七次：舍身无量。</p><button disabled={added} onClick={()=>onCopyMaterial({id:"verse",title:"无相还真旧教页",kind:"缓存教页",url:"https://www.zhuyinwen.cn/archive/cache/baishesong-1986.html"})} style={{minHeight:48,display:"inline-flex",alignItems:"center",justifyContent:"center",gap:9,marginTop:18,padding:"0 18px",border:added?"1px solid #5e4a45":"2px solid #a34e43",background:added?"#211b19":"#3b1714",color:added?"#8b7d76":"#f0d7c8",borderRadius:7,fontSize:13,fontWeight:800,cursor:added?"default":"pointer",boxShadow:added?"none":"0 8px 24px #0008"}}><FilePlus2 size={18}/><span>{added?"已加入调查材料":"添加到调查材料"}</span></button></article></section></main>}

